version: "2"

linters:
  default: none
  enable:
    - ineffassign
    - govet
    - misspell
    - revive
    - unused
    - goconst
    - forbidigo
    - predeclared
  settings:
    revive:
      rules:
        - name: confusing-naming
          disabled: true
        - name: exported
          disabled: true
    goconst:
      min-len: 2
      min-occurrences: 10
      match-constant: true
    forbidigo:
      forbid:
        - pattern: ^.*\.Sleep.*$
          msg: "No sleeps please use the appropriate polls and watch"
        - pattern: ^fmt\.Print.*$
          msg: "No format prints, please testing or logrus packages"
  exclusions:
    generated: strict
    paths:
      - pkg/generated
      - clients/rancher/generated
      - .*\.yaml$
      - .*\.yml$

formatters:
  enable:
    - goimports

run:
  tests: false
  timeout: 10m