linters:
  disable-all: true
  enable:
  - ineffassign
  - goimports
  - govet
  - misspell
  - revive
  - unused
  - goconst
  - forbidigo
  - predeclared
  - gochecknoglobals
linters-settings:
  revive:
    rules:
    - name: confusing-naming
      disabled: true
    - name: exported
      disabled: false
  goconst: 
    min-len: 2
    min-occurrences: 10
    match-constant: true
    ignore-strings: "metadata.+"
  forbidigo:
    forbid:
      - p: ^*\.Sleep.*$
        msg: "No sleeps please use the appropriate polls and watch"
      - p: ^fmt\.Print.*$
        msg: "No format prints, please testing or logrus packages"
run:
  tests: false
  timeout: 10m
issues:
  exclude-dirs:
    - pkg/generated/*
    - clients/rancher/generated/*
  exclude-rules:
    #Scheme and v3 schemas are being skipped due to the complexity of updating the global vars used in Shepherd clients
    - path: pkg/*
      linters:
        - gochecknoglobals
  exclude-files:
    - ^*\.yaml$
    - ^*\.yml$
  exclude-generated-strict: true
